const toasts = [
	'Is it a good day to stay in bed? Maybe. Is it a good day to get up? Also maybe.',
	'Remember when you thought being an adult would solve all your problems? Haha, yeah.',
	'The universe is vast and full of mysteries. Like, where did you leave your keys?',
	'Sometimes, all you need is a snack. Sometimes, all you have is existential dread.',
	'You ever feel like life is just a series of loading screens?',
	"The stars are out tonight. They don't have any answers, but they look nice.",
	"Some days, you're the protagonist. Other days, you're an NPC in someone else's story.",
	"Why does pizza taste better at 2 AM? Science can't explain it, but it's true.",
	"It's okay to be a little lost. The map was probably written in another language anyway.",
	'Remember: You don’t have to have everything figured out. Who even wrote that rule?',
	'There’s comfort in the small things. Like socks. Socks are good.',
	"You are not a failure. You're just in a cutscene. It'll pass.",
	'Coffee is great, but have you tried existential dread? Pairs well with morning fog.',
	'You know, sometimes it’s okay to let the dishes sit for another day. They’re patient.',
	"Why do we dream? Maybe it's just the brain's way of taking a coffee break.",
	"Remember: Even the moon has its dark side. So, you're in good company.",
	"Life is like a video game. Sometimes you just need to hit 'restart.'",
	"Is anyone really 'normal'? Asking for a friend. And also, for myself.",
	"Do you ever just... stare at the ceiling and wonder what it's all about?",
	'Even the trees are just trying their best. Be like the trees.',
	'You’re not lazy. You’re conserving energy for something important. Probably.',
	'The truth is out there. But so are distractions.',
	'Remember when you didn’t know what a bill was? Good times.',
	'The sun will rise again tomorrow. And maybe, so will you.',
	'It’s okay to not have all the answers. The internet doesn’t either.',
	'Take a deep breath. And another. Okay, that’s enough for now.',
	'The future is a mystery. Which is exciting. And also terrifying.',
	"You're doing better than you think. But also, naps are good.",
	'Is it just me, or does life feel like one big quick-time event?',
	'Not every day has to be productive. Some days just need to exist.',
	'Cats don’t worry about the meaning of life. Be more like a cat.',
	'It’s okay to ask for help. Even heroes need a sidekick.',
	'You don’t have to be perfect. Flaws add character. Or so they say.',
	'Sometimes, it’s okay to be the storm. Other times, be the rainbow.',
	'Your worth isn’t measured by productivity. You’re allowed to just be.',
	'You don’t need to save the world today. Maybe just save yourself some stress.',
	'Life’s a journey. It’s okay if you get lost along the way.',
	'Not every day is an adventure. Some days are just side quests.',
	"The stars don't worry about their place in the sky. Take note.",
	'You don’t have to carry the world on your shoulders. It’s okay to let go.',
	'It’s okay to be tired. The universe is heavy.',
	'You are not alone. Even if it feels like it sometimes.',
	"There's no rush. Life isn't a race, and if it is, what’s the prize?",
	'You don’t have to know where you’re going. Just keep moving.',
	'Some days are for moving mountains. Others are for watching clouds.',
	'You can’t control everything. But you can control your snack choices.',
	"Your story matters, even if it’s just beginning. Or if it's the middle. Or the end.",
	'Remember: The journey is more important than the destination. But the destination is nice too.',
	'It’s okay to feel small. The universe is big, but that doesn’t make you any less significant.',
	"You're not lost, you're just exploring.",
	'It’s okay to not be okay. Seriously.',
	'You’ve got this. And even if you don’t, that’s okay too.',
	'You’re allowed to change. The stars do it all the time.',
	'Take time to appreciate the little things. Like breathing. Breathing’s important.',
	'You’re not a burden. You’re just carrying too much right now.',
	'It’s okay to take a break. Even the universe pauses sometimes.',
	'Somewhere, something amazing is happening. And you’re part of it.',
	'Even if today is hard, remember that tomorrow is another chance.',
	"Sometimes, you need to remind yourself that it's okay to be human.",
	'There’s beauty in the chaos. You just have to squint a little.',
	'You are enough. Always have been, always will be.',
	'Remember to be kind to yourself. You deserve it.',
	'Your path is your own. It doesn’t have to look like anyone else’s.',
	'The stars aren’t always visible, but they’re always there. So are you.',
	'Life’s a puzzle. Don’t worry if you haven’t found all the pieces yet.',
	'You’re a work in progress. And that’s perfectly okay.',
	'Sometimes, you need to sit in the dark to appreciate the light.',
	'Not every day needs a happy ending. Sometimes, it just needs an ending.',
	'You are doing your best. And that’s enough.',
	'It’s okay to not have everything figured out. Life’s a weird, winding road.',
	'Remember when you were a kid and thought you’d have it all together by now? Joke’s on us.',
	'You don’t have to make every day count. Some days just exist.',
	'It’s okay to be a little broken. The light gets in through the cracks.',
	'You don’t need to rush. Life’s more of a meander anyway.',
	'You are a cosmic being. But also, you probably need more sleep.',
	'Sometimes, it’s okay to just watch the world go by.',
	'The world is strange, and so are you. Embrace it.',
	'It’s okay to feel like a mess. We all do, sometimes.',
	'You don’t have to be strong all the time. It’s okay to rest.',
	'Not all who wander are lost. Some are just taking the scenic route.',
	'Even the stars have their bad days. You’re allowed to have them too.',
	'You are more resilient than you realize. Keep going.',
	'There’s a place for you in this universe. You belong here.',
	'It’s okay to feel out of place. The universe is a big, weird place.',
	'You don’t have to be perfect to be worth something.',
	'Sometimes, the best thing you can do is just show up.',
	'You’re allowed to have bad days. It doesn’t make you any less important.',
	'Remember, it’s okay to ask for directions. Even the best explorers do.',
	'The night is dark, but so is coffee. You got this.',
	'It’s okay to dream, even if the dreams are weird and full of plot holes.',
	'You’re a story in progress. Don’t worry about the edits.',
	'You don’t need to be a hero. Being you is enough.',
	'Sometimes, the best way to find yourself is to get a little lost.',
	'You are stardust, and that’s pretty cool.',
	'It’s okay if today wasn’t your day. There’s always tomorrow.',
	'Remember: The universe is big, but you are important.',
	'You don’t have to be a star to shine. Sometimes, just being is enough.',
	'Sometimes, the hardest part is just starting. But you’ve got this.',
	'The world is weird. But hey, so are you. Own it.',
	'You’re doing better than you think. Progress isn’t always obvious.',
	"It's okay if the best part of today was a nap.",
	'You’re not stuck. You’re just waiting for your next adventure.',
	'The stars may be out of reach, but dreams aren’t.',
	'You don’t have to carry the weight of the world. It’s heavy.',
	'Even the clouds take a break. You should too.',
	'It’s okay to not know what’s next. Just keep moving forward.',
	'You are enough, even when it feels like you aren’t.',
	'There’s no rush. Life unfolds in its own time.',
	'You can’t control everything, but you can control your response.',
	'Not all days will be good, but there’s good in every day.',
	'You’re allowed to feel lost. It’s part of finding your way.',
	'You don’t need to have all the answers right now. Or ever.',
	'The universe isn’t in a hurry. Why should you be?',
	'You’re not alone. Even when it feels like it.',
	'It’s okay to be scared. It means you’re human.',
	'You’re a work in progress. That’s a good thing.',
	'Sometimes, the best you can do is just breathe. And that’s enough.',
	'The night is quiet, but your thoughts don’t have to be.',
	'You’re more resilient than you give yourself credit for.',
	'You don’t need to rush. Life is more of a stroll than a sprint.',
	'It’s okay to take things one step at a time.',
	'The stars might be far away, but you’re here, and that matters.',
	'You don’t need to be perfect. You just need to be.',
	'It’s okay to let go of what’s weighing you down.',
	'The world is full of possibilities. You just need to look.',
	'You’re allowed to have bad days. It doesn’t define you.',
	'The night is long, but so is the journey. Keep going.',
	'You’re not behind. You’re on your own path.',
	'It’s okay to ask for help. No one does this alone.',
	'You’re more than your mistakes. You’re a whole story.',
	'The stars don’t worry about shining. They just do.',
	'You’re doing your best. That’s all anyone can ask.',
	'It’s okay to take a break. The world will still be there.',
	'You’re allowed to feel how you feel. Don’t apologize for it.',
	'Sometimes, the best way to move forward is to pause.',
	'You’re not a burden. You’re just going through something.',
	'The night is dark, but you are a light.',
	'You’re not alone in feeling alone. We’re all in this together.',
	'You don’t have to have it all figured out. Who does?',
	'It’s okay to feel small. The universe is big, but so is your heart.',
	'You’re allowed to dream big, even if it feels impossible.',
	'The stars don’t rush. Neither should you.',
	'You’re not a failure. You’re learning. And that’s powerful.',
	'It’s okay to rest. Even the earth takes a break every night.',
	'You’re allowed to change. In fact, it’s encouraged.',
	'The night is quiet, but your dreams are loud. Listen to them.',
	'You’re not defined by your past. You’re more than that.',
	'It’s okay to be uncertain. That’s where discovery happens.',
	'You’re more than just your achievements. You’re a whole person.',
	'The stars don’t judge. Neither should you.',
	'You’re not alone in your struggle. We all have our battles.',
	'It’s okay to be vulnerable. That’s where true strength lies.',
	'You’re not a mistake. You’re a work in progress.',
	'The night may be long, but it’s not forever.',
	'You’re allowed to feel tired. This world is exhausting.',
	'It’s okay to start over. New beginnings are powerful.',
	'You’re not just existing. You’re living. And that’s enough.',
	'The stars are watching. They believe in you.',
	'You’re not a robot. You’re allowed to have emotions.',
	'It’s okay to need time to figure things out.',
	'You’re more capable than you think. Trust yourself.',
	'The night is for dreaming. So dream big.',
	'You’re allowed to take up space. This world is yours too.',
	'It’s okay to not be okay. Seriously.',
	'You’re not invisible. You matter.',
	'The stars don’t worry about tomorrow. Neither should you.',
	'You’re allowed to be happy, even if things aren’t perfect.',
	'It’s okay to feel overwhelmed. This world is a lot.',
	'You’re more than your productivity. You’re a person.',
	'The night may be dark, but you are a light.',
	'You’re allowed to ask for what you need.',
	'It’s okay to take a break from everything.',
	'You’re more resilient than you know.',
	'The stars don’t rush to shine. Neither should you.',
	'You’re allowed to be a little selfish sometimes.',
	'It’s okay to not have a plan.',
	'You’re more than enough. Always have been, always will be.',
	'The night is quiet, but your thoughts are loud. That’s okay.',
	'You’re allowed to change your mind. It’s part of growth.',
	'It’s okay to let yourself feel all the emotions.',
	'You’re not just surviving. You’re thriving in your own way.',
	'The stars aren’t always visible, but they’re always there. So are you.',
	'You’re allowed to be imperfect. Perfection is overrated.',
	'It’s okay to take it one day at a time.',
	'You’re more than your struggles. You’re so much more.',
	'The night may be long, but you are strong.',
	'You’re allowed to set boundaries. They’re important.',
	'It’s okay to not have everything figured out.',
	'You’re more than your past. You’re your future too.',
	'The stars don’t ask for permission to shine. Neither should you.',
	'You’re allowed to take up space in this world. It’s yours too.',
	'It’s okay to be confused. The best stories are full of twists.',
	'You don’t need to have it all together. No one really does.',
	'The night is quiet, but your soul can be loud. Let it be.',
	'You’re allowed to outgrow who you used to be.',
	'It’s okay to feel stuck. Sometimes, that’s just a pause before the leap.',
	'You’re more than your worst days.',
	'The stars don’t compare themselves to each other. Neither should you.',
	'You’re allowed to make mistakes. They’re part of learning.',
	'It’s okay to feel like you don’t have all the answers.',
	'You’re stronger than you think. But it’s okay to ask for help too.',
	'The night is long, but every minute brings you closer to dawn.',
	'You don’t need permission to be yourself.',
	'It’s okay to let go of things that no longer serve you.',
	'You’re allowed to be proud of how far you’ve come.',
	'The stars don’t need validation. Neither do you.',
	'You’re not the sum of your flaws. You’re so much more.',
	'It’s okay to feel everything all at once. That’s being human.',
	'You’re allowed to change your path. It’s your journey.',
	'The night is vast, but so is your potential.',
	'You don’t need to rush to catch up. You’re right where you need to be.',
	'It’s okay to not be okay. It’s part of the process.',
	'You’re allowed to protect your peace.',
	'The stars don’t worry about shining perfectly. They just do.',
	'You’re not just a passenger in your life. You’re the driver.',
	'It’s okay to take a step back to see the bigger picture.',
	'You’re allowed to be imperfect. That’s what makes you real.',
	'The night may be silent, but your thoughts are heard.',
	'You don’t need to justify your feelings. They’re valid.',
	'It’s okay to dream of something different.',
	'You’re allowed to find joy in small moments.',
	'The stars don’t need to be seen to be real. Neither do your dreams.',
	'You’re not obligated to be the same person you were yesterday.',
	'It’s okay to be a little lost. The best adventures start that way.',
	'You’re allowed to feel deeply. It means you’re alive.',
	'The night is full of mystery, and so are you.',
	'You don’t need to be everything for everyone.',
	'It’s okay to take your time. Life isn’t a race.',
	'You’re allowed to walk away from what’s hurting you.',
	'The stars don’t apologize for existing. Neither should you.',
	'You’re not too much. You’re just enough.',
	'It’s okay to not have a plan. Life will still unfold.',
	'You’re allowed to celebrate your small victories.',
	'The night is for resting. Let your worries rest too.',
	'You don’t need to prove your worth. You are worthy.',
	'It’s okay to ask for a break. You’re human.',
	'You’re allowed to grow in ways others might not understand.',
	'The stars don’t judge your journey. Neither should you.',
	'You’re not behind. You’re on your own timeline.',
	'It’s okay to say no. It’s a complete sentence.',
	'You’re allowed to embrace the unknown.',
	'The night is your canvas. Paint it with your thoughts.',
	'You don’t need to have it all figured out to take the next step.',
	'It’s okay to take care of yourself first.',
	'You’re allowed to feel like you belong, because you do.',
	'The stars don’t rush. They know they’ll shine eventually.',
	'You’re not broken. You’re just in the process of becoming whole.',
	'It’s okay to need time to heal.',
	'You’re allowed to start over as many times as you need.',
	'The night is dark, but it brings clarity too.',
	'You don’t need to be anyone else. You’re perfectly you.',
	'It’s okay to let go of expectations.',
	'You’re allowed to be a work in progress and a masterpiece at the same time.',
	'The stars don’t stress about tomorrow. Neither should you.',
	'You’re not alone. Even in your loneliest moments.',
	'It’s okay to choose what’s best for you, even if it’s hard.',
	'You’re allowed to take up space in this world.',
	'The night is peaceful, but it’s okay if your mind isn’t.',
	'You don’t need to have all the answers. Curiosity is enough.',
	'It’s okay to set boundaries. They’re acts of self-care.',
	'You’re allowed to dream of more.',
	'The stars don’t follow a script. They shine in their own way.',
	'You’re not too late. Your timing is perfect for you.',
	'It’s okay to feel vulnerable. It means you’re human.',
	'You’re allowed to trust yourself.',
	'The night may seem endless, but dawn always comes.',
	'You don’t need to have everything figured out to be worthy of love.',
	'It’s okay to take a detour. Sometimes, it’s where the best views are.',
	'You’re allowed to be proud of yourself.',
	'The stars don’t compete. They shine together.',
	'You’re not defined by what others think of you.',
	'It’s okay to choose yourself.',
	'You’re allowed to take life one moment at a time.',
	'The night is quiet, but your thoughts are vibrant.',
	'You don’t need to explain your journey to anyone.',
	'It’s okay to feel everything you’re feeling.',
	'You’re allowed to embrace your weirdness. It’s what makes you, you.',
	'The stars don’t wait for approval to shine. Neither should you.',
	'You’re not just existing. You’re making your way.',
	'It’s okay to take your time healing.',
	'You’re allowed to take up space and be heard.',
	'The night is dark, but your light is brighter.',
	'You don’t need to be anyone else but yourself.',
	'It’s okay to feel uncertain. Life is full of surprises.',
	'You’re allowed to be your own hero.',
	'The stars don’t doubt their place. Neither should you.',
	'It’s okay to take your time finding your way.',
	'You’re allowed to prioritize your peace.',
	'The night is calm, but it’s okay if you’re not.',
	'You don’t have to be everything to everyone.',
	'It’s okay to sit with your thoughts, even the messy ones.',
	'You’re allowed to be exactly who you are, no apologies.',
	'The stars don’t rush their brilliance. Neither should you.',
	'You’re not alone in feeling like you don’t belong. But you do.',
	'It’s okay to need a little extra time to figure things out.',
	'You’re allowed to rest without guilt.',
	'The night is full of possibilities. So are you.',
	'You don’t have to force things to happen. Let them flow.',
	'It’s okay to feel like a work in progress.',
	'You’re allowed to protect your energy.',
	'The stars don’t need to be seen to be beautiful. Neither do you.',
	'You’re not the same person you were yesterday. That’s growth.',
	'It’s okay to take a step back to breathe.',
	'You’re allowed to change your mind about what you want.',
	'The night is still, but your mind doesn’t have to be.',
	'You don’t have to conform to fit in. You’re perfect as you are.',
	'It’s okay to walk your own path, even if it’s different.',
	'You’re allowed to feel proud of how far you’ve come.',
	'The stars don’t measure their worth. Neither should you.',
	'You’re not obligated to carry others’ expectations.',
	'It’s okay to focus on your own journey.',
	'You’re allowed to be uncertain and still move forward.',
	'The night is a reminder that peace is possible.',
	'You don’t have to explain your choices to anyone.',
	'It’s okay to need space to recharge.',
	'You’re allowed to embrace who you are becoming.',
	'The stars don’t wait for permission to shine. Neither should you.',
	'You’re not less for needing time alone.',
	'It’s okay to take things slow.',
	'You’re allowed to make mistakes and learn from them.',
	'The night is a canvas for your dreams.',
	'You don’t have to have it all figured out right now.',
	'It’s okay to not have all the answers. No one does.',
	'You’re allowed to say no without feeling guilty.',
	'The stars don’t apologize for their existence. Neither should you.',
	'You’re not defined by your setbacks.',
	'It’s okay to let go of what’s no longer serving you.',
	'You’re allowed to put yourself first.',
	'The night is a reminder that even in darkness, there’s light.',
	'You don’t need to be anyone else but yourself.',
	'It’s okay to be a little selfish with your time.',
	'You’re allowed to take breaks and rest.',
	'The stars don’t compete. They shine together.',
	'You’re not obligated to please everyone.',
	'It’s okay to feel a little lost sometimes.',
	'You’re allowed to follow your intuition.',
	'The night is for dreaming big.',
	'You don’t need to have everything planned out.',
	'It’s okay to be exactly where you are.',
	'You’re allowed to set boundaries to protect your peace.',
	'The stars don’t worry about tomorrow. Neither should you.',
	'You’re not just surviving. You’re thriving in your own way.',
	'It’s okay to let yourself be happy.',
	'You’re allowed to embrace change, even when it’s scary.',
	'The night is quiet, but your heart can be loud.',
	'You don’t have to prove your worth to anyone.',
	'It’s okay to be proud of your progress.',
	'You’re allowed to grow at your own pace.',
	'The stars don’t need an audience to shine. Neither do you.',
	'You’re not too late. Your timing is just right.',
	'It’s okay to feel like you’re still figuring things out.',
	'You’re allowed to trust the process, even when it’s uncertain.',
	'The night is a reminder that rest is important.',
	'You don’t have to be perfect. You just need to be you.',
	'It’s okay to take time for yourself.',
	'You’re allowed to change directions whenever you need to.',
	'The stars don’t worry about being enough. Neither should you.',
	'You’re not alone in your journey.',
	'It’s okay to embrace your quirks. They make you unique.',
	'You’re allowed to be a work in progress.',
	'The night is calm, but your soul can be wild.',
	'You don’t have to have it all together.',
	'It’s okay to take small steps forward.',
	'You’re allowed to find beauty in the little things.',
	'The stars don’t stress about tomorrow. Neither should you.',
	'You’re not just existing. You’re creating your story.',
	'It’s okay to not know what’s next.',
	'You’re allowed to embrace your journey, wherever it takes you.',
	'The night is a reminder that even in darkness, there is hope.',
	'You don’t have to be everything to everyone.',
	'It’s okay to put yourself first sometimes.',
	'You’re allowed to feel all your feelings.',
	'The stars don’t need to be perfect. Neither do you.',
	'You’re not just here to survive. You’re here to thrive.',
	'It’s okay to dream, even if the dream feels far away.',
	'You’re allowed to take your time healing.',
	'The night is peaceful, and you can be too.',
	'You don’t need to rush your journey.',
	'It’s okay to set boundaries that protect your peace.',
	'You’re allowed to be a little lost and still be on the right path.',
	'The stars don’t rush their journey. Neither should you.',
	'You’re not just surviving. You’re learning to thrive.',
	'It’s okay to take your time to rest and recharge.',
	'You’re allowed to be proud of your growth.',
	'The night is still, but your dreams can be wild.',
	'It’s okay to seek comfort in the small things.',
	'You’re allowed to rewrite your story whenever you want.',
	'The night may be dark, but your spirit is bright.',
	'You don’t need to have it all figured out to take the first step.',
	'It’s okay to take life one breath at a time.',
	'You’re allowed to cherish the quiet moments.',
	'The stars don’t worry about being perfect. Neither should you.',
	'You’re not alone in feeling overwhelmed.',
	'It’s okay to slow down and enjoy the journey.',
	'You’re allowed to let go of what’s not yours to carry.',
	'The night is for dreaming of possibilities.',
	'You don’t have to rush your growth. It’s happening naturally.',
	'It’s okay to find joy in the little things.',
	'You’re allowed to feel proud of how far you’ve come.',
	'The stars don’t need validation to shine. Neither do you.',
	'You’re not defined by your mistakes. You’re defined by how you rise.',
	'It’s okay to embrace the unknown.',
	'You’re allowed to feel deeply and still move forward.',
	'The night may be silent, but your heart can still sing.',
	'You don’t have to be everything to everyone. Just be yourself.',
	'It’s okay to seek peace in the chaos.',
	'You’re allowed to change your mind and your direction.',
	'The stars don’t ask for permission to shine. Neither should you.',
	'You’re not alone in your journey, even when it feels that way.',
	'It’s okay to put your own needs first.',
	'You’re allowed to take up space and be heard.',
	'The night is long, but so is your strength.',
	'You don’t need to compare yourself to anyone else.',
	'It’s okay to be proud of your resilience.',
	'You’re allowed to be both a masterpiece and a work in progress.',
	'The stars don’t rush. They know they’ll shine in their time.',
	'You’re not just surviving. You’re learning to thrive.',
	'It’s okay to take things slow. There’s no need to hurry.',
	'You’re allowed to be exactly who you are, no matter what.',
	'The night is a reminder that it’s okay to rest.',
	'You don’t have to do it all alone. It’s okay to ask for help.',
	'It’s okay to not have all the answers right now.',
	'You’re allowed to take time to figure things out.',
	'The stars don’t need to be perfect to shine. Neither do you.',
	'You’re not defined by your struggles. You’re defined by your strength.',
	'It’s okay to need time to recharge.',
	'You’re allowed to create your own path.',
	'The night is quiet, but your dreams are loud.',
	'You don’t need to be perfect to be worthy.',
	'It’s okay to find joy in the little victories.',
	'You’re allowed to be exactly where you are in your journey.',
	'The stars don’t stress. They just shine.',
	'You’re not alone in feeling like you don’t have it all together.',
	'It’s okay to be gentle with yourself.',
	'You’re allowed to change your mind as often as you need to.',
	'The night is a canvas for your dreams. Paint it boldly.',
	'You don’t have to follow anyone else’s path but your own.',
	'It’s okay to take a break from the world.',
	'You’re allowed to feel all your emotions, even the messy ones.',
	'The stars don’t wait for approval. Neither should you.',
	'You’re not just getting by. You’re doing your best, and that’s enough.',
	'It’s okay to need time to heal.',
	'You’re allowed to set boundaries to protect your energy.',
	'The night is for resting, and so are you.',
	'You don’t have to have everything figured out to move forward.',
	'It’s okay to be a little uncertain about the future.',
	'You’re allowed to dream big, even if it scares you.',
	'The stars don’t judge your journey. Neither should you.',
	'You’re not defined by your past. You’re creating your future.',
	'It’s okay to take your time finding your way.',
	'You’re allowed to take a break and rest.',
	'The night may be dark, but your heart is full of light.',
	'You don’t need to be perfect. You just need to be you.',
	'It’s okay to let go of what no longer serves you.',
	'You’re allowed to feel all your feelings and still keep going.',
	'The stars don’t compete. They just shine.',
	'You’re not alone in your journey. We’re all finding our way.',
	'It’s okay to choose yourself first.',
	'You’re allowed to take your time healing.',
	'The night is for dreaming, and your dreams matter.',
	'You don’t have to rush your growth. It’s happening naturally.',
	'It’s okay to feel everything deeply. It means you’re alive.',
	'You’re allowed to rewrite your story at any time.',
	'The stars don’t apologize for existing. Neither should you.',
	'You’re not too late. You’re right on time for your life.',
	'It’s okay to be proud of your progress.',
	'You’re allowed to take your time figuring things out.',
	'The night is quiet, but your dreams can be loud.',
	'You don’t need to have it all figured out to be okay.',
	'It’s okay to be a little lost. That’s how you find your way.',
	'You’re allowed to embrace the journey, even when it’s uncertain.',
	'The stars don’t rush to shine. Neither should you.',
	'You’re not just surviving. You’re learning to thrive in your own way.',
	'It’s okay to take a break and rest your mind.',
	'You’re allowed to feel proud of your journey.',
	'The night is peaceful, and you deserve peace too.',
	'You don’t need to have everything planned out.',
	'It’s okay to feel a little lost sometimes. We all do.',
	'You’re allowed to take up space and be yourself.',
	'It’s okay to feel overwhelmed. The night has its own way of calming.',
	'You’re allowed to take time to find your peace.',
	'The stars don’t worry about their place in the sky. Neither should you.',
	'You don’t need to have a perfect plan. Taking the next step is enough.',
	'It’s okay to embrace the uncertainty of the journey.',
	'You’re allowed to be kind to yourself, always.',
	'The night is for reflection and dreaming. Let your mind wander.',
	'You don’t have to fit into anyone’s expectations but your own.',
	'It’s okay to be a little lost. It means you’re exploring.',
	'You’re allowed to change your path whenever you need to.',
	'The stars don’t compete. They simply shine. So should you.',
	'You’re not alone in feeling like you don’t have it all together.',
	'It’s okay to take a break from everything and just breathe.',
	'You’re allowed to find comfort in small moments of peace.',
	'The night is a canvas for your hopes and dreams. Paint it vividly.',
	'You don’t need to be perfect to be loved.',
	'It’s okay to be a work in progress. Growth takes time.',
	'You’re allowed to seek out joy, even in the midst of challenges.',
	'The stars don’t rush their brilliance. You don’t need to rush yours.',
	'You’re not defined by your setbacks. You’re defined by how you rise.',
	'It’s okay to set boundaries to protect your mental space.',
	'You’re allowed to take your time to heal and grow.',
	'The night is quiet, but your thoughts can be full of possibilities.',
	'You don’t have to justify your feelings. They are valid.',
	'It’s okay to need time to process and understand.',
	'You’re allowed to embrace the unknown and trust the process.',
	'The stars don’t stress about their place. They simply shine.',
	'You’re not alone in feeling like you’re on a winding path.',
	'It’s okay to seek out moments of calm in the chaos.',
	'You’re allowed to be exactly where you are in your journey.',
	'The night is for dreaming and discovering new possibilities.',
	'You don’t need to have all the answers to start moving forward.',
	'It’s okay to embrace your journey, even when it’s unclear.',
	'You’re allowed to find peace in the process, not just the outcome.',
	'The stars don’t apologize for their light. Neither should you.',
	'You’re not alone in feeling like you’re figuring things out.',
	'It’s okay to find solace in the quiet moments of the night.',
	'You’re allowed to take a step back and reassess.',
	'The night is full of potential. So are you.',
	'You don’t have to be anything other than yourself.',
	'It’s okay to feel unsure. It’s a natural part of growth.',
	'You’re allowed to set your own pace in life’s journey.',
	'The stars don’t need to be perfect. They just need to shine.',
	'You’re not defined by your fears. You’re defined by your courage.',
	'It’s okay to embrace your uniqueness.',
	'You’re allowed to take time to find your own rhythm.',
	'The night is a reminder that even in darkness, there is hope.',
	'You don’t need to rush to meet others’ expectations.',
	'It’s okay to rest and recharge when you need to.',
	'You’re allowed to find strength in vulnerability.',
	'The stars don’t measure their worth. Neither should you.',
	'You’re not alone in needing time to figure things out.',
	'It’s okay to let yourself feel and process emotions.',
	'You’re allowed to find joy in the small moments.',
	'The night is quiet, but your dreams are loud and vivid.',
	'You don’t have to have everything sorted out to be okay.',
	'It’s okay to take your time finding your way.',
	'You’re allowed to be proud of your progress, no matter how small.',
	'The stars don’t need validation to shine. Neither do you.',
	'You’re not defined by your past mistakes. You’re defined by your growth.',
	'It’s okay to take a moment to rest and gather your thoughts.',
	'You’re allowed to embrace the journey, even when it’s uncertain.',
	'The night is a time for reflection and renewal.',
	'You don’t need to be perfect. Just be your authentic self.',
	'It’s okay to need a break from the hustle and bustle.',
	'You’re allowed to feel a range of emotions and still keep moving forward.',
	'The stars don’t rush their brilliance. You don’t need to rush yours.',
	'You’re not alone in your struggles. We all have our battles.',
	'It’s okay to set boundaries and protect your well-being.',
	'You’re allowed to take time for yourself without guilt.',
	'The night is for dreaming big and finding inspiration.',
	'You don’t have to follow anyone else’s path. Create your own.',
	'It’s okay to be a little lost. It means you’re exploring new possibilities.',
	'You’re allowed to take up space and be seen.',
	'The stars don’t compete for attention. They just shine.',
	'You’re not defined by your fears or doubts.',
	'It’s okay to need time to figure things out.',
	'You’re allowed to feel all your feelings and still move forward.',
	'The night is full of potential. Let your dreams take flight.',
	'You don’t have to be everything for everyone. Just be yourself.',
	'It’s okay to find solace in the quiet moments.',
	'You’re allowed to embrace change and growth.',
	'The stars don’t apologize for their light. Neither should you.',
	'You’re not alone in needing time to process and heal.',
	'It’s okay to take things one step at a time.',
	'You’re allowed to find joy in the small victories along the way.',
	'The night is a reminder that even in darkness, there’s beauty.',
	'It’s okay to take life one step at a time.',
	'You’re allowed to embrace the quiet moments.',
	'The stars don’t rush to shine. They simply do.',
	'You don’t need to have all the answers to begin.',
	'It’s okay to feel uncertain and still move forward.',
	'You’re allowed to create your own path.',
	'The night is calm, and you can be too.',
	'You don’t have to conform to anyone’s expectations.',
	'It’s okay to take a break and breathe.',
	'You’re allowed to find your own way, even if it’s different.',
	'The stars don’t compare themselves. Neither should you.',
	'You’re not alone in your journey. We’re all figuring it out.',
	'It’s okay to feel vulnerable. It’s part of being human.',
	'You’re allowed to set boundaries that protect your peace.',
	'The night is for rest and reflection. Take your time.',
	'You don’t have to be perfect. You just have to be yourself.',
	'It’s okay to seek out what brings you joy.',
	'You’re allowed to be proud of the small victories.',
	'The stars don’t need to be perfect. Neither do you.',
	'You’re not defined by your past. You’re creating your future.',
	'It’s okay to take your time figuring things out.',
	'You’re allowed to feel all your emotions without judgment.',
	'The night is quiet, but your dreams are loud and clear.',
	'You don’t need to have it all together to be worthy.',
	'It’s okay to take life at your own pace.',
	'You’re allowed to find peace in the small things.',
	'The stars don’t ask for permission to shine. Neither should you.',
	'You’re not alone in feeling lost sometimes.',
	'It’s okay to let go of what no longer serves you.',
	'You’re allowed to embrace your journey, even when it’s messy.',
	'The night is a canvas for your thoughts and dreams.',
	'You don’t have to follow anyone else’s timeline.',
	'It’s okay to take a moment to rest and recharge.',
	'You’re allowed to be exactly where you are right now.',
	'The stars don’t need to prove their worth. Neither do you.',
	'You’re not defined by your struggles. You’re defined by your strength.',
	'It’s okay to take things slow and steady.',
	'You’re allowed to find comfort in the stillness.',
	'The night is a reminder that it’s okay to rest.',
	'You don’t have to do it all on your own.',
	'It’s okay to feel a little lost. It means you’re exploring.',
	'You’re allowed to take time for yourself.',
	'The stars don’t rush their light. Neither should you.',
	'You’re not alone in your journey. We all walk our own paths.',
	'It’s okay to feel deeply and still move forward.',
	'You’re allowed to set boundaries to protect your energy.',
	'The night is for reflection. Take time to think.',
	'You don’t need to have everything figured out.',
	'It’s okay to seek peace in the quiet moments.',
	'You’re allowed to change your mind whenever you need to.',
	'The stars don’t compete. They shine together.',
	'You’re not defined by your fears. You’re defined by your actions.',
	'It’s okay to take your time and move at your own pace.',
	'You’re allowed to feel all your feelings, even the tough ones.',
	'The night is for dreaming. Let your dreams take flight.',
	'You don’t have to be perfect to be enough.',
	'It’s okay to find joy in the little things.',
	'You’re allowed to be a work in progress.',
	'The stars don’t apologize for shining. Neither should you.',
	'You’re not alone in your struggles. We all have our challenges.',
	'It’s okay to take things one step at a time.',
	'You’re allowed to embrace the journey, even when it’s hard.',
	'The night is a reminder that peace is possible.',
	'You don’t have to rush through life. Take your time.',
	'It’s okay to find solace in the quiet moments.',
	'You’re allowed to be exactly who you are.',
	'The stars don’t need to be perfect. Neither do you.',
	'You’re not defined by your past. You’re shaping your future.',
	'It’s okay to need time to heal and grow.',
	'You’re allowed to find beauty in the small moments.',
	'The night is for rest and renewal.',
	'You don’t need to have it all figured out to be okay.',
	'It’s okay to take a break and just breathe.',
	'You’re allowed to set your own pace and direction.',
	'The stars don’t worry about tomorrow. Neither should you.',
	'You’re not alone in feeling uncertain about the future.',
	'It’s okay to take life one day at a time.',
	'You’re allowed to be kind to yourself.',
	'The night is quiet, but your dreams can be loud.',
	'You don’t have to follow anyone else’s path. Create your own.',
	'It’s okay to take a moment to appreciate how far you’ve come.',
	'You’re allowed to be exactly where you are in your journey.',
	'The stars don’t compete. They simply shine.',
	'You’re not defined by your fears or doubts.',
	'It’s okay to need time to process and heal.',
	'You’re allowed to find joy in the journey, not just the destination.',
	'The night is for dreaming and reflecting.',
	'You don’t have to be everything to everyone.',
	'It’s okay to put yourself first sometimes.',
	'You’re allowed to take time to find your way.',
	'The stars don’t rush their journey. Neither should you.',
	'It’s okay to find strength in the quiet moments.',
	'You’re allowed to take life at your own pace.',
	'The stars don’t hurry their glow. Neither should you.',
	'You don’t need to have everything figured out to be okay.',
	'It’s okay to find comfort in the simple things.',
	'You’re allowed to take a break when you need to.',
	'The night is peaceful, and you deserve peace too.',
	'You don’t have to meet anyone else’s expectations.',
	'It’s okay to feel a little lost sometimes.',
	'You’re allowed to be a work in progress.',
	'The stars don’t worry about the darkness. They just shine.',
	'You’re not alone in feeling like you’re still figuring things out.',
	'It’s okay to let go of things that no longer serve you.',
	'You’re allowed to take a moment to just breathe.',
	'The night is a time for reflection. Let your mind wander.',
	'You don’t have to do it all. It’s okay to rest.',
	'It’s okay to embrace the journey, even if it’s unclear.',
	'You’re allowed to find your own rhythm.',
	'The stars don’t rush their brilliance. Neither should you.',
	'You’re not defined by your past. You’re creating your future.',
	'It’s okay to take a break from the world.',
	'You’re allowed to feel deeply and still move forward.',
	'The night is quiet, but your dreams are loud and clear.',
	'You don’t need to have it all together. Just take it one step at a time.',
	'It’s okay to embrace your uniqueness.',
	'You’re allowed to find joy in the small victories.',
	'The stars don’t apologize for their light. Neither should you.',
	'You’re not alone in your struggles. We all have them.',
	'It’s okay to take things slow and steady.',
	'You’re allowed to seek out what makes you happy.',
	'The night is for dreaming. Let your dreams soar.',
	'You don’t have to be perfect to be loved.',
	'It’s okay to take your time and move at your own pace.',
	'You’re allowed to be exactly who you are.',
	'The stars don’t need to be perfect. Neither do you.',
	'You’re not defined by your fears. You’re defined by your courage.',
	'It’s okay to need time to figure things out.',
	'You’re allowed to find peace in the small things.',
	'The night is a reminder that it’s okay to rest.',
	'You don’t need to have everything planned out.',
	'It’s okay to feel a little uncertain and still keep going.',
	'You’re allowed to take time to find your own way.',
	'The stars don’t rush their light. Neither should you.',
	'You’re not alone in feeling like you’re on a winding path.',
	'It’s okay to take a moment to appreciate the journey.',
	'You’re allowed to feel all your emotions without judgment.',
	'The night is for reflection. Take time to think.',
	'You don’t need to be everything for everyone.',
	'It’s okay to find solace in the quiet moments.',
	'You’re allowed to set your own pace in life.',
	'The stars don’t compete for attention. They simply shine.',
	'You’re not defined by your past mistakes. You’re defined by your growth.',
	'It’s okay to take life one day at a time.',
	'You’re allowed to be kind to yourself.',
	'The night is a reminder that even in darkness, there is hope.',
	'You don’t have to follow anyone else’s path.',
	'It’s okay to be proud of your progress.',
	'You’re allowed to take your time figuring things out.',
	'The stars don’t stress. They just shine.',
	'You’re not alone in your journey. We’re all finding our way.',
	'It’s okay to embrace your journey, even when it’s hard.',
	'You’re allowed to find joy in the process, not just the outcome.',
	'The night is peaceful, and you deserve peace too.',
	'You don’t need to rush your growth. It’s happening naturally.',
	'It’s okay to find comfort in the small things.',
	'You’re allowed to take a break when you need to.',
	'The stars don’t rush to shine. Neither should you.',
	'You’re not alone in feeling like you’re still figuring things out.',
	'It’s okay to let go of what no longer serves you.',
	'You’re allowed to find your own rhythm.',
	'The night is for dreaming and reflecting.',
	'You don’t have to be perfect to be enough.',
	'It’s okay to be a work in progress.',
	'You’re allowed to take up space and be seen.',
	'The stars don’t compete. They simply shine.',
	'You’re not defined by your fears or doubts.',
	'It’s okay to take time to heal and grow.',
	'You’re allowed to find beauty in the small moments.',
	'The night is for rest and renewal.',
	'You don’t need to have it all figured out to be okay.',
	'It’s okay to take things one step at a time.',
	'You’re allowed to be exactly where you are in your journey.',
	'The stars don’t rush their journey. Neither should you.',
	'You’re not alone in feeling uncertain about the future.',
	'It’s okay to take a moment to rest and recharge.',
	'You’re allowed to find your own path, even if it’s different.',
	'The night is quiet, but your dreams can be loud.',
	'You don’t need to follow anyone else’s timeline.',
	'It’s okay to embrace the unknown and trust the process.',
	'You’re allowed to find peace in the quiet moments.',
	'The stars don’t compare themselves. Neither should you.',
	'You’re not defined by your struggles. You’re defined by your strength.',
	'It’s okay to set boundaries to protect your peace.',
	'You’re allowed to be exactly who you are, no matter what.',
	'The night is a reminder that even in darkness, there’s beauty.',
	'You don’t need to be everything to everyone. Just be yourself.',
	'It’s okay to find joy in the little things.',
	'You’re allowed to take time for yourself without guilt.',
	'The stars don’t apologize for their light. Neither should you.',
	'You’re not alone in needing time to process and heal.',
	'It’s okay to feel everything deeply. It means you’re alive.',
	'You’re allowed to rewrite your story at any time.',
	'The night is a canvas for your thoughts and dreams.',
	'You don’t have to rush through life. Take your time.',
	'It’s okay to pause and reflect on where you are.',
	'You’re allowed to find strength in vulnerability.',
	'The stars shine brightest in the darkest nights. So can you.',
	'You don’t need to have a clear path to move forward.',
	'It’s okay to take time to discover what you truly want.',
	'You’re allowed to change directions and try new things.',
	'The night is a space for your dreams and aspirations.',
	'You don’t have to rush through the healing process.',
	'It’s okay to seek solace in the small, quiet moments.',
	'You’re allowed to be proud of the progress you’ve made.',
	'The stars don’t need to compete for light. Neither do you.',
	'You’re not alone in feeling like you’re on a journey.',
	'It’s okay to find comfort in familiar routines.',
	'You’re allowed to take time to understand yourself better.',
	'The night offers a chance for reflection and renewal.',
	'You don’t need to meet others’ expectations to be valuable.',
	'It’s okay to take a step back and reassess your path.',
	'You’re allowed to feel uncertain and still keep going.',
	'The stars don’t measure their brightness. They simply shine.',
	'You’re not defined by your doubts. You’re defined by your courage.',
	'It’s okay to find peace in the quiet moments of your life.',
	'You’re allowed to embrace change and growth.',
	'The night is for dreaming, so let your imagination soar.',
	'You don’t have to have it all figured out to be okay.',
	'It’s okay to let yourself be vulnerable and authentic.',
	'You’re allowed to take breaks and give yourself space.',
	'The stars don’t judge each other’s light. They just shine together.',
	'You’re not alone in needing time to heal.',
	'It’s okay to take life at your own pace.',
	'You’re allowed to find joy in your journey, even in the small moments.',
	'The night is a reminder that rest is part of the process.',
	'You don’t need to be perfect to be loved.',
	'It’s okay to take a moment to appreciate your own growth.',
	'You’re allowed to be exactly who you are, no matter what.',
	'The stars don’t rush their brilliance. Neither should you.',
	'You’re not defined by your setbacks. You’re defined by your resilience.',
	'It’s okay to seek out moments of calm amidst the chaos.',
	'You’re allowed to embrace the journey, even when it’s unclear.',
	'The night is for reflection and dreaming. Let yourself explore.',
	'You don’t have to follow anyone else’s path but your own.',
	'It’s okay to take your time and move at your own pace.',
	'You’re allowed to find strength in the quiet moments.',
	'The stars don’t need to compete. They shine in their own time.',
	'You’re not alone in feeling like you’re figuring things out.',
	'It’s okay to set boundaries that protect your well-being.',
	'You’re allowed to find beauty in the journey.',
	'The night is for dreaming big and finding inspiration.',
	'You don’t have to have everything figured out to be okay.',
	'It’s okay to take a step back and just breathe.',
	'You’re allowed to feel all your emotions without judgment.',
	'The stars don’t apologize for shining. Neither should you.',
	'You’re not defined by your fears or insecurities.',
	'It’s okay to take things one day at a time.',
	'You’re allowed to seek comfort and find peace in the quiet moments.',
	'The night is a space for renewal and rest.',
	'You don’t need to rush through the process of growth.',
	'It’s okay to embrace the unknown and trust your journey.',
	'You’re allowed to take time for yourself without feeling guilty.',
	'The stars don’t rush their light. They simply shine.',
	'You’re not alone in needing to take things slow.',
	'It’s okay to take time to understand your own needs and desires.',
	'You’re allowed to find solace in the stillness of the night.',
	'The night is for dreaming and reflecting on your journey.',
	'You don’t have to meet anyone’s expectations but your own.',
	'It’s okay to find joy in the process of discovery.',
	'You’re allowed to take breaks and give yourself space to grow.',
	'The stars don’t worry about their place in the sky. Neither should you.',
	'You’re not defined by your struggles. You’re defined by how you rise above them.',
	'It’s okay to seek out moments of peace amidst the chaos.',
	'You’re allowed to embrace your journey, even when it’s challenging.',
	'The night is a time for rest and reflection.',
	'You don’t need to be perfect to be worthy of love and respect.',
	'It’s okay to take things at your own pace and in your own time.',
	'You’re allowed to find beauty in the small, everyday moments.',
	'The stars don’t compete for attention. They shine in their own way.',
	'You’re not alone in feeling uncertain about the future.',
	'It’s okay to take a moment to appreciate how far you’ve come.',
	'You’re allowed to set boundaries that help you feel safe and valued.',
	'The night is for dreaming and finding your own path.',
	'You don’t have to have it all figured out to be okay.',
	'It’s okay to be gentle with yourself and take things one step at a time.',
	'You’re allowed to find comfort and peace in the quiet moments.',
	'The stars don’t rush their brilliance. You don’t need to rush yours.',
	'You’re not defined by your mistakes. You’re defined by your ability to learn and grow.',
	'It’s okay to seek out what brings you joy and fulfillment.',
	'You’re allowed to take time for yourself and prioritize your well-being.',
	'The night is a reminder that even in darkness, there is light.',
	'You don’t need to be anything other than yourself.',
	'It’s okay to feel a little lost sometimes. It means you’re exploring new possibilities.',
	'You’re allowed to take breaks and give yourself space to breathe.',
	'The stars don’t compete for brightness. They shine in their own way.',
	'You’re not alone in needing to take things slow and steady.',
	'It’s okay to take time to figure out what you truly want.',
	'You’re allowed to be proud of your progress, no matter how small.',
	'It’s okay to take a moment to reflect on your journey.',
	'You’re allowed to feel proud of how far you’ve come, even if the path isn’t clear.',
	'The stars don’t need to compete for light. Neither do you.',
	'You don’t have to have all the answers right now.',
	'It’s okay to let yourself rest and recharge.',
	'You’re allowed to find beauty in the small, everyday moments.',
	'The night is a time for dreaming and introspection.',
	'You don’t need to be perfect to be worthy of love and respect.',
	'It’s okay to take things one step at a time.',
	'You’re allowed to find solace in the quiet moments.',
	'The stars don’t rush their brilliance. They simply shine.',
	'You’re not alone in feeling uncertain about your path.',
	'It’s okay to seek out what brings you peace and comfort.',
	'You’re allowed to take breaks and give yourself space.',
	'The night is for reflection and renewal.',
	'You don’t have to meet anyone’s expectations but your own.',
	'It’s okay to embrace the journey, even when it’s difficult.',
	'You’re allowed to find joy in the small victories along the way.',
	'The stars don’t measure their brightness. They simply exist.',
	'You’re not defined by your setbacks. You’re defined by your resilience.',
	'It’s okay to let yourself feel all your emotions.',
	'You’re allowed to change your direction and try new things.',
	'The night is a canvas for your dreams and hopes.',
	'You don’t need to have everything figured out to be okay.',
	'It’s okay to be kind to yourself and take things slowly.',
	'You’re allowed to find peace in the stillness of the night.',
	'The stars don’t worry about their place. They just shine.',
	'You’re not alone in feeling like you’re on a journey.',
	'It’s okay to seek moments of calm and rest.',
	'You’re allowed to embrace your unique path.',
	'The night is for dreaming big and finding inspiration.',
	'You don’t need to rush through the healing process.',
	'It’s okay to take a step back and appreciate your progress.',
	'You’re allowed to be exactly where you are in your journey.',
	'The stars don’t compete for attention. They shine together.',
	'You’re not defined by your fears. You’re defined by your courage.',
	'It’s okay to find solace in the quiet moments.',
	'You’re allowed to take your time and move at your own pace.',
	'The night is a reminder that rest is part of the journey.',
	'You don’t have to be perfect to be loved and valued.',
	'It’s okay to feel a little lost. It means you’re exploring new possibilities.',
	'You’re allowed to take breaks and give yourself space to grow.',
	'The stars don’t need validation to shine. Neither do you.',
	'You’re not alone in needing time to figure things out.',
	'It’s okay to take life one day at a time.',
	'You’re allowed to find joy in the journey, not just the destination.',
	'The night is a space for reflection and renewal.',
	'You don’t need to have it all together to be okay.',
	'It’s okay to seek out moments of peace amidst the chaos.',
	'You’re allowed to find strength in vulnerability.',
	'The stars don’t rush their brilliance. You don’t need to rush yours.',
	'You’re not defined by your struggles. You’re defined by how you overcome them.',
	'It’s okay to take time for yourself and prioritize your well-being.',
	'You’re allowed to embrace change and growth.',
	'The night is for dreaming and exploring new possibilities.',
	'You don’t have to conform to anyone’s expectations but your own.',
	'It’s okay to be gentle with yourself and take things one step at a time.',
	'You’re allowed to find comfort in the small moments of peace.',
	'The stars don’t apologize for their light. Neither should you.',
	'You’re not alone in feeling like you’re figuring things out.',
	'It’s okay to take a moment to appreciate how far you’ve come.',
	'You’re allowed to set boundaries that protect your mental space.',
	'The night is for dreaming big and finding inspiration.',
	'You don’t need to have everything figured out to move forward.',
	'It’s okay to find joy in the journey, even in the small moments.',
	'You’re allowed to take time to understand yourself better.',
	'The stars don’t rush their light. They shine in their own time.',
	'You’re not defined by your doubts or insecurities.',
	'It’s okay to embrace the unknown and trust your path.',
	'You’re allowed to take breaks and give yourself space to heal.',
	'The night is a reminder that peace and rest are part of the journey.',
	'You don’t have to meet anyone’s expectations but your own.',
	'It’s okay to be proud of your progress, no matter how small.',
	'You’re allowed to find strength in the quiet moments of the night.',
	'The stars don’t measure their light. They simply shine.',
	'You’re not alone in needing time to process and grow.',
	'It’s okay to seek comfort and peace in the familiar.',
	'You’re allowed to find beauty in the small victories along the way.',
	'The night is for reflection and dreaming.',
	'You don’t need to be perfect to be enough.',
	'It’s okay to take things one day at a time.',
	'You’re allowed to be kind to yourself and take your time.',
	'The stars don’t compete for brilliance. They shine in their own way.',
	'It’s okay to not have everything figured out yet.',
	'You’re allowed to find comfort in the journey, even when it’s uncertain.',
	'The stars don’t rush to shine. They just do.',
	'You don’t need to be perfect to be valuable.',
	'It’s okay to take time to appreciate the small things.',
	'You’re allowed to feel all your emotions and still move forward.',
	'The night is a canvas for your dreams and hopes.',
	'You don’t have to meet others’ expectations to find your path.',
	'It’s okay to take breaks and give yourself space to breathe.',
	'You’re allowed to embrace the journey, even when it’s challenging.',
	'The stars don’t compete for light. They simply shine.',
	'You’re not alone in feeling like you’re on a winding path.',
	'It’s okay to find solace in the quiet moments of the night.',
	'You’re allowed to take your time and grow at your own pace.',
	'The night is for rest and reflection. Let yourself recharge.',
	'You don’t need to have all the answers to be okay.',
	'It’s okay to be proud of the progress you’ve made, no matter how small.',
	'You’re allowed to find joy in the everyday moments.',
	'The stars don’t measure their brilliance. They just exist.',
	'You’re not defined by your fears. You’re defined by your resilience.',
	'It’s okay to seek out what brings you peace and comfort.',
	'You’re allowed to take time for yourself and prioritize your well-being.',
	'The night is a reminder that even in darkness, there is light.',
	'You don’t have to follow anyone else’s path but your own.',
	'It’s okay to take a step back and reassess your direction.',
	'You’re allowed to embrace change and growth.',
	'The stars don’t need validation to shine. Neither do you.',
	'You’re not alone in needing to take things slowly.',
	'It’s okay to let yourself feel and process your emotions.',
	'You’re allowed to find strength in the quiet moments.',
	'The night is a space for dreaming and reflecting.',
	'You don’t need to be perfect to be worthy of love and respect.',
	'It’s okay to take life one day at a time.',
	'You’re allowed to find beauty in the small, everyday victories.',
	'The stars don’t apologize for their light. Neither should you.',
	'You’re not defined by your setbacks. You’re defined by how you overcome them.',
	'It’s okay to seek out moments of calm and peace.',
	'You’re allowed to take breaks and give yourself space to grow.',
	'The night is a reminder that rest is a crucial part of the journey.',
	'You don’t have to have it all together to be okay.',
	'It’s okay to embrace your unique path and journey.',
	'You’re allowed to find comfort in familiar routines.',
	'The stars don’t rush their brilliance. You don’t need to rush yours.',
	'You’re not alone in feeling like you’re figuring things out.',
	'It’s okay to take time to understand your own needs and desires.',
	'You’re allowed to be gentle with yourself and take things slowly.',
	'The night is for dreaming big and finding inspiration.',
	'You don’t need to meet others’ expectations to be valued.',
	'It’s okay to find solace in the small, quiet moments.',
	'You’re allowed to take time for yourself and prioritize your well-being.',
	'The stars don’t measure their worth. They simply shine.',
	'You’re not alone in needing time to heal and grow.',
	'It’s okay to feel deeply and still move forward.',
	'You’re allowed to set boundaries that protect your mental space.',
	'The night is a reminder that even in darkness, there is hope.',
	'You don’t have to be perfect to be loved.',
	'It’s okay to take a moment to appreciate your progress.',
	'You’re allowed to find strength in vulnerability.',
	'The stars don’t compete for light. They shine in their own way.',
	'You’re not defined by your doubts or fears.',
	'It’s okay to embrace the unknown and trust the process.',
	'You’re allowed to take breaks and give yourself space to recharge.',
	'The night is for rest and reflection. Let yourself rejuvenate.',
	'You don’t need to have everything figured out to be okay.',
	'It’s okay to take things one step at a time.',
	'You’re allowed to find joy in the journey, not just the destination.',
	'The stars don’t worry about their place in the sky. They just shine.',
	'You’re not alone in feeling uncertain about your future.',
	'It’s okay to find comfort in the familiar and the routine.',
	'You’re allowed to take time to heal and grow.',
	'The night is a space for your dreams and hopes.',
	'You don’t have to meet anyone else’s expectations but your own.',
	'It’s okay to be proud of your progress, no matter how small.',
	'You’re allowed to find peace in the quiet moments.',
	'The stars don’t rush their brilliance. You don’t need to rush yours.',
	'You’re not defined by your struggles. You’re defined by your resilience.',
	'It’s okay to seek moments of calm amidst the chaos.',
	'You’re allowed to embrace change and growth.',
	'The night is for dreaming big and finding your own path.',
	'You don’t have to be perfect to be worthy of love and respect.',
	'It’s okay to take a step back and appreciate your journey.',
	'You’re allowed to take time for yourself and prioritize your well-being.'
];

export const load = async ({ fetch }) => {
	// Function to get n random elements from an array
	const getRandomElements = (arr, n) => {
		const shuffled = arr.slice().sort(() => 0.5 - Math.random());
		return shuffled.slice(0, n);
	};

	// Get 50 random toasts
	const randomToasts = getRandomElements(toasts, 50);

	// Return the random toasts
	return {
		toasts: randomToasts
	};
};
